services:
  backend:
    image: charlotter678/peakrentbackend:latest
    env_file:
      - database.env
      - variables.env
    command: npm start
    depends_on:
      - db

  frontend:
    image: charlotter678/peakrentfrontend:latest
    environment:
      VITE_PUBLIC_STRIPE_KEY: ${VITE_PUBLIC_STRIPE_KEY}
      URL_REST: ${URL_REST}
    command: ["npx", "serve", "dist", "--single"]
    depends_on:
      - backend

  db:
    image: postgres
    container_name: postgres-production
    ports:
      - "3030:5432"
    env_file:
      - database.env
    volumes:
      - dbdata:/var/lib/postgresql

  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx
      - ./logs/prod:/var/log/nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend

volumes:
  dbdata:
    driver: local
