services:
  backend:
    build: ./backend-GraphQL
    ports:
      - 5050:5000
    command: npm run dev
    volumes:
      - ./backend-GraphQL/src:/app/src
      - ./backend-GraphQL/good_corner.sqlite:/app/good_corner.sqlite
      - ./backend-GraphQL/queries.sql:/app/queries.sql
      - ./backend-GraphQL/tsconfig.json:/app/tsconfig.json
    networks:
      - my_network

  frontend:
    build: ./frontend
    ports:
      - 3000:5173
    command: npm run dev
    depends_on:
      - backend
    volumes:
      - ./frontend/index.html:/app/index.html
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/vite.config.ts:/app/vite.config.ts
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
