services:
  backend:
    image: charlotter678/peakrentbackend:staging
    env_file:
      - database.env
      - variables.env
    command: npm start
    depends_on:
      - db

  frontend:
    image: charlotter678/peakrentfrontend:staging
    command: npm run dev
    env_file:
      - front.variables.env
    depends_on:
      - backend

  db:
    image: postgres
    container_name: postgres-staging
    ports:
      - 3030:5432
    env_file:
      - database.env
    volumes:
      - dbdata:/var/lib/postgresql

  nginx:
    image: nginx
    container_name: nginx-staging
    volumes:
      - ./nginx-staging:/etc/nginx
      - ./logs/staging:/var/log/nginx
    ports:
      - "8001:80"
    depends_on:
      - backend
      - frontend

volumes:
  dbdata:
    driver: local
