services:
  backend:
    build: ./backend
    ports:
      - 5050:4000
    env_file:
      - database.env
      - variables.env
    volumes:
      - ./backend/src:/app/src
      - ./backend/tsconfig.json:/app/tsconfig.json
    command: npm start
    # command: [
    #     "/bin/bash",
    #     "-c",
    #     "
    #     echo 'Waiting for Postgres to be ready...';
    #     sleep 10;

    #     echo 'Running seed script...';
    #     npx ts-node src/seed.ts;

    #     echo 'Starting the backend...';
    #     npm start
    #     ",
    #   ]

  frontend:
    build: ./frontend
    ports:
      - 3000:5173
    command: npm run dev
    depends_on:
      - backend
    volumes:
      - ./frontend/index.html:/app/index.html
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/vite.config.ts:/app/vite.config.ts

  db:
    image: postgres
    ports:
      - 5555:5432
      # - 5555 / 3030 / 8080
    env_file:
      - database.env
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
    driver: local
