services:
  backend:
    image: charlotter678/peakrentbackend
    env_file:
      - database.env
      - variables.env
    command: npm start
    depends_on:
      - db

  frontend:
    image: charlotter678/peakrentfrontend
    command: npm run dev
    depends_on:
      - backend

  db:
    image: postgres
    ports:
      - 5555:5432
    env_file:
      - database.env
    volumes:
      - dbdata:/var/lib/postgresql/data

  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - "8001:80"
    depends_on:
      - backend
      - frontend

volumes:
  dbdata:
    driver: local
