export const forwardProducts = [
  {
    id: 1,
    name: "Ski freestyle rossignol",
    price: 3000,
    tags: ["ski", "expert"],
    image: "/product.png",
    discount: 30,
    color: "yellow",
    slug: "/skis-yellow",
  },
  {
    id: 2,
    name: "Ski freestyle rossignol long titre",
    price: 3000,
    tags: ["ski", "débutant"],
    image: "/product.png",
    discount: 0,
    color: "blue",
    slug: "/skis-blue",
  },
  {
    id: 3,
    name: "Ski freestyle rossignol tres long long long long titre",
    price: 3000,
    tags: ["ski", "débutant"],
    image: "/product.png",
    discount: 20,
    color: "yellow",
    slug: "/skis-yellow",
  },
  {
    id: 4,
    name: "Ski freestyle rossignol",
    price: 3000,
    tags: ["ski", "débutant"],
    image: "/product.png",
    discount: 50,
    color: "blue",
    slug: "/skis-blue",
  },
  {
    id: 5,
    name: "Ski freestyle rossignol",
    price: 5500,
    tags: ["ski", "expert"],
    image: "/product.png",
    discount: 10,
    color: "blue",
    slug: "/skis-blue",
  },
  {
    id: 6,
    name: "Ski freestyle rossignol",
    price: 3333,
    tags: ["ski", "medium"],
    image: "/product.png",
    discount: 20,
    color: "blue",
    slug: "/skis-blue",
  },
  {
    id: 7,
    name: "Ski freestyle rossignol",
    price: 3333,
    tags: ["ski", "medium"],
    image: "/product.png",
    discount: 0,
    color: "blue",
    slug: "/skis-blue",
  },
  {
    id: 8,
    name: "Ski freestyle rossignol",
    price: 3333,
    tags: ["ski", "medium"],
    image: "/product.png",
    discount: 0,
    color: "blue",
    slug: "/skis-blue",
  },
  {
    id: 9,
    name: "Ski freestyle rossignol",
    price: 3333,
    tags: ["ski", "medium"],
    image: "/product.png",
    discount: 60,
    color: "blue",
    slug: "/skis-blue",
  },
  {
    id: 10,
    name: "Ski freestyle rossignol",
    price: 3333,
    tags: ["ski", "medium"],
    image: "/product.png",
    discount: 30,
    color: "blue",
    slug: "/skis-blue",
  },
];

export const carousselImages = [
  { src: "/image-1.png", alt: "Slide 1" },
  { src: "/image-2.png", alt: "Slide 2" },
  { src: "/image-3.png", alt: "Slide 3" },
  { src: "/image-4.png", alt: "Slide 4" },
  { src: "/image-5.png", alt: "Slide 5" },
];

export const homeActivities = [
  {
    title: "Activité 1",
    description: "Description de l'activité 1",
    image: "/image-1.png",
  },
  {
    title: "Activité 2",
    description: "Description de l'activité 2",
    image: "/image-2.png",
  },
  {
    title: "Activité 3",
    description: "Description de l'activité 3",
    image: "/image-3.png",
  },
  {
    title: "Activité 4",
    description: "Description de l'activité 4",
    image: "/image-1.png",
  },
  {
    title: "Activité 5",
    description: "Description de l'activité 5",
    image: "/image-2.png",
  },
  {
    title: "Activité 6",
    description: "Description de l'activité 6",
    image: "/image-3.png",
  },
  {
    title: "Activité 7",
    description: "Description de l'activité 7",
    image: "/image-3.png",
  },
  {
    title: "Activité 8",
    description: "Description de l'activité 8",
    image: "/image-3.png",
  },
  {
    title: "Activité 9",
    description: "Description de l'activité 9",
    image: "/image-3.png",
  },
];
