import { Calendar, Heart, Store, Wallet } from "lucide-react";

export const forwardProducts = [
  {
    id: 1,
    name: "Ski freestyle rossignol",
    price: 3000,
    tags: ["ski", "expert"],
    image: "/product.png",
    discount: 30,
    color: "yellow",
    slug: "/skis-yellow",
  },
  {
    id: 2,
    name: "Ski freestyle rossignol long titre",
    price: 3000,
    tags: ["ski", "débutant"],
    image: "/product.png",
    discount: 0,
    color: "blue",
    slug: "/skis-blue",
  },
  {
    id: 3,
    name: "Ski freestyle rossignol tres long long long long titre",
    price: 3000,
    tags: ["ski", "confirmé"],
    image: "/product.png",
    discount: 20,
    color: "yellow",
    slug: "/skis-yellow",
  },
  {
    id: 4,
    name: "Ski freestyle rossignol",
    price: 3000,
    tags: ["ski", "medium"],
    image: "/product.png",
    discount: 50,
    color: "blue",
    slug: "/skis-blue",
  },
  {
    id: 5,
    name: "Ski freestyle rossignol",
    price: 5500,
    tags: ["ski", "expert"],
    image: "/product.png",
    discount: 10,
    color: "blue",
    slug: "/skis-blue",
  },
  {
    id: 6,
    name: "Ski freestyle rossignol",
    price: 3333,
    tags: ["ski", "medium"],
    image: "/product.png",
    discount: 20,
    color: "blue",
    slug: "/skis-blue",
  },
  {
    id: 7,
    name: "Ski freestyle rossignol",
    price: 3333,
    tags: ["ski", "medium"],
    image: "/product.png",
    discount: 0,
    color: "blue",
    slug: "/skis-blue",
  },
  {
    id: 8,
    name: "Ski freestyle rossignol",
    price: 3333,
    tags: ["ski", "medium"],
    image: "/product.png",
    discount: 0,
    color: "blue",
    slug: "/skis-blue",
  },
  {
    id: 9,
    name: "Ski freestyle rossignol",
    price: 3333,
    tags: ["ski", "medium"],
    image: "/product.png",
    discount: 60,
    color: "blue",
    slug: "/skis-blue",
  },
  {
    id: 10,
    name: "Ski freestyle rossignol",
    price: 3333,
    tags: ["ski", "medium"],
    image: "/product.png",
    discount: 30,
    color: "blue",
    slug: "/skis-blue",
  },
];

export const carousselImages = [
  { src: "/image-1.png", alt: "Slide 1" },
  { src: "/image-2.png", alt: "Slide 2" },
  { src: "/image-3.png", alt: "Slide 3" },
  { src: "/image-4.png", alt: "Slide 4" },
  { src: "/image-5.png", alt: "Slide 5" },
];

export const homeActivities = [
  {
    id: 1,
    title: "Activité 1",
    description: "Description de l'activité 1",
    image: "/image-1.png",
    span: "row-span-2 col-span-3",
  },
  {
    id: 2,
    title: "Activité 2",
    description: "Description de l'activité 2",
    image: "/image-2.png",
    span: "col-span-3",
  },
  {
    id: 3,
    title: "Activité 3",
    description: "Description de l'activité 3",
    image: "/image-3.png",
    span: "col-span-2",
  },
  {
    id: 4,
    title: "Activité 4",
    description: "Description de l'activité 4",
    image: "/image-1.png",
    span: "col-span-2",
  },
  {
    id: 5,
    title: "Activité 5",
    description: "Description de l'activité 5",
    image: "/image-2.png",
    span: "col-span-2",
  },
  {
    id: 6,
    title: "Activité 6",
    description: "Description de l'activité 6",
    image: "/image-3.png",
    span: "col-span-2",
  },
  {
    id: 7,
    title: "Activité 7",
    description: "Description de l'activité 7",
    image: "/image-3.png",
    span: "col-span-3",
  },
  {
    id: 8,
    title: "Activité 8",
    description: "Description de l'activité 8",
    image: "/image-3.png",
    span: "col-span-2",
  },
  {
    id: 9,
    title: "Activité 9",
    description: "Description de l'activité 9",
    image: "/image-3.png",
    span: "col-span-3",
  },
];

export const rentalProcessSteps = [
  {
    icon: <Calendar className="size-6 text-red-500" />,
    title: "Reservez",
    description: "Réservez vos équipements dans le magasin de votre choix.",
  },
  {
    icon: <Wallet className="size-6 text-red-500" />,
    title: "Payez",
    description:
      "Que ce soit seul ou à plusieurs, payez en ligne ou directement en magasin.",
  },
  {
    icon: <Heart className="size-6 text-red-500" />,
    title: "Profitez",
    description:
      "Profitez de nos équipement de qualité sans vous soucier du reste !",
  },
  {
    icon: <Store className="size-6 text-red-500" />,
    title: "Retournez",
    description: "Retournez les équipements dans le magasin de votre choix.",
  },
];
