name: ci-build-develop

on:
  push:
    branches:
      - develop

jobs:
  build-frontend-develop:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:frontend"
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_FRONTEND_STAGING_REPO }}:latest, ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_FRONTEND_STAGING_REPO }}:${{ github.sha }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build-backend-develop:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:backend"
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_BACKEND_STAGING_REPO }}:latest, ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_BACKEND_STAGING_REPO }}:${{ github.sha }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
